[package]
name = "envmgr"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
nix = { version = "0.29.0", features = ["mount"] }
karen = "0.1.2"
xdg = "2.5.2"
clap = { version = "4.5.9", features = ["derive"] }
users = "0.11.0"